---
- name: "Setup {{ ansible_facts['distribution_release'] }}-backports distribution"
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: "{{ ansible_facts['distribution_release'] }}-backports"
  loop:
    - "deb http://deb.debian.org/debian {{ ansible_facts['distribution_release'] }}-backports main contrib"
    - "deb-src http://deb.debian.org/debian {{ ansible_facts['distribution_release'] }}-backports main contrib"
  notify: apt_update

- name: Copy apt preferences file
  template:
    src: 90zfs.j2
    dest: /etc/apt/preferences.d/90zfs
    mode: '0644'
    backup: yes
  notify: apt_update

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

# The `ansible_facts['architecture']` variable works in most cases, but
# reports `amd64` as `x86_64`, which is not desired in this case.
# The `ansible_facts['kernel']` variable is also a good alternative, but
# is not as portable as just using the architecture variable.
# The following is a workaround that only works in Debian-based
# operating systems.
- name: Get architecture
  shell: dpkg --print-architecture
  register: dpkg_architecture

- name: Install kernel headers
  apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: yes
  vars:
    packages:
    - "linux-headers-{{ dpkg_architecture.stdout }}"
    - "linux-image-{{ dpkg_architecture.stdout }}"

- name: Install other dependencies
  apt:
    name: dpkg-dev
    state: present
    force_apt_get: yes

- name: Install DKMS
  apt:
    name: dkms
    state: present
    default_release: "{{ ansible_facts['distribution_release'] }}-backports"
    force_apt_get: yes

# Installs minimum zfs-dkms files to run modprobe command
- name: Install ZFS-DKMS
  apt:
    name: zfs-dkms
    state: present
    default_release: "{{ ansible_facts['distribution_release'] }}-backports"
    force_apt_get: yes
    install_recommends: no

- name: Load ZFS module
  modprobe:
    name: zfs
    state: present

- name: Install ZFS
  apt:
    name: zfsutils-linux
    state: present
    default_release: "{{ ansible_facts['distribution_release'] }}-backports"
    force_apt_get: yes
